title: Sagui NLP
description: Research • Tools • Papers
url: https://sagui-nlp.github.io
baseurl: ""        # keep empty for org root
markdown: kramdown # default on GitHub Pages/Jekyll
kramdown:
  math_engine: katex
permalink: /:categories/:year/:month/:day/:title/
collections:
  members:
    output: true
  papers:
    output: true

